name: Automatically Update Dependencies
on:
  pull_request_target:
    types: [labeled]

jobs:
  auto-merge-dependency-updates:
    runs-on: ubuntu-latest
    steps:
    - name: Enable Github Automerge
      uses: alexwilson/enable-github-automerge-action@2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
      if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')

  auto-approve-dependency-updates:
    needs: auto-merge-dependency-updates
    runs-on: ubuntu-latest
    steps:
      - id: auto-approve-dependabot
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
